trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    if ! dpkg-query -W -f='${Status}' ffmpeg | grep "ok installed"; then sudo apt update && sudo apt install ffmpeg; fi
  displayName: 'Install ffmpeg (test dependency) if not already installed'
- script: npm install
  displayName: 'Run install packages'
- script: |
    npm run ci
  displayName: 'Run Build/lint/test'
- task: Npm@1
  inputs:
    command: 'publish'
    publishEndpoint: 'Npm registry'
- script: |
    npm run test:coverage
  displayName: 'Publish test coverage'
- publish: /usr/bin/ffmpeg
  artifact: apt cache
