
jobs:
  - default
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: npm install
      displayName: 'Run install pacakges'
    - script: |
        npm run build
      displayName: 'Run Build'

  - master
    trigger:
    - master
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: npm install
      displayName: 'Run install pacakges'
    - script: |
        npm run build
      displayName: 'Run Build'
    - task: Npm@1
      inputs:
        command: 'publish'
        publishEndpoint: 'Npm registry'
    