
  pool:
    vmImage: 'ubuntu-latest'
  trigger:
    branches:
      include:
      - *
      exclude:
      - master
  steps:
  - script: npm install
    displayName: 'Run install packages'
  - script: |
      sudo apt update && sudo apt install ffmpeg
    displayName: 'Install ffmpeg (test dependency)'
  - script: |
      npm run ci
    displayName: 'Run Build/lint/test'
  - publish: /var/cache/apt/archives
    artifact: apt cache
  