
  pool:
    vmImage: 'ubuntu-latest'
  trigger:
    branches:
      include:
      - '*'
      exclude:
      - master
  steps:
  - script: npm install
    displayName: 'Run install packages'
  - script: |
      if ! dpkg-query -W -f='${Status}' ffmpe | grep "ok installed"; then sudo apt update && sudo apt install ffmpeg; fi
    displayName: 'Install ffmpeg (test dependency) if not already installed'
  - script: |
      npm run ci
    displayName: 'Run Build/lint/test'
  - publish: /usr/bin/ffmpeg
    artifact: apt cache
  