
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: npm install
    displayName: 'Run install packages'
  - script: |
      sudo apt update && sudo apt install ffmpeg
    displayName: 'Install ffmpeg (test dependency)'
  - script: |
      npm run ci
    displayName: 'Run Build/lint/test'
  