trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    sudo apt update && sudo apt install ffmpeg
  displayName: 'Install ffmpeg (test dependency)'
- script: |
    npm run ci
  displayName: 'Run Build/lint/test'
- task: Npm@1
  inputs:
    command: 'publish'
    publishEndpoint: 'Npm registry'
